name: Deploy Haddock Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true

      - name: Generate Haddock documentation
        run: stack haddock --no-haddock-deps

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .stack-work/install/*/*/doc
